# Generated by Django 3.1.4 on 2025-02-01 14:37

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20250201_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
